version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app                  # سینک کردن پروژه با کانتینر
      - media_volume:/app/media # volume برای ذخیره تصاویر آپلود شده
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
      - ALLOWED_HOSTS=*

volumes:
  media_volume:
