# Generated by Django 5.2.5 on 2025-10-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True, default='Unknown address', null=True, verbose_name='Project Address'),
        ),
        migrations.AddField(
            model_name='project',
            name='floors_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Floors'),
        ),
        migrations.AddField(
            model_name='project',
            name='municipal_file_number',
            field=models.CharField(default=0, help_text='Unique municipal file number for each project.', max_length=50, unique=True, verbose_name='Municipal File Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_name',
            field=models.CharField(default='Unknown Owner', max_length=100, verbose_name='Owner Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Project Area (m²)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived'), ('active', 'Active')], default='active', max_length=16, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(default='No summary provided.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['municipal_file_number'], name='catalog_pro_municip_e7e9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='catalog_pro_status_2f7597_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_35036a_idx'),
        ),
    ]
